trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: oph/oph.ado.templates

extends:
  template: pipeline.yml@templates
  parameters:
    projectName: oph.tf.env

    build:
      projectType: cloud
      tfChildDir: ./module
